#pragma once

#include <cstdint>

#include "DatabaseTypes.h"
#include "Implementation/IMSDatabase.h"

namespace database::Implementation
{

enum class AMSPreparedStatement : std::uint32_t
{
    ACCOUNT_TEST_PING = static_cast<std::uint32_t>(IMSPreparedStatement::MAX_VALUE),

    // ticket table
    DB_TICKET_INSERT_NEW_TICKET,
    DB_TICKET_SELECT_TICKET_BY_ID,
    DB_TICKET_SELECT_ALL_TICKETS,
    DB_TICKET_OVERVIEW_SELECT,
    DB_TICKET_OVERVIEW_SELECT_SINCE,
    DB_TICKET_OVERVIEW_SELECT_REMOVED_SINCE,
    DB_TICKET_OVERVIEW_SELECT_LAST_COMMENT_BY_ID,
    DB_TICKET_UPDATE_TICKET_STATUS_BY_ID,
    DB_TICKET_UPDATE_TICKET_PRIORITY_BY_ID,
    DB_TICKET_UPDATE_TICKET_TITLE_BY_ID,
    DB_TICKET_UPDATE_TICKET_DESCRIPTION_BY_ID,
    DB_TICKET_UPDATE_TICKET_TO_CLOSED_BY_ID,

    // ticket_assignment table
    DB_TA_INSERT_NEW_TICKET_ASSIGNMENT,
    DB_TA_INSERT_NEW_ASSIGNMENT_WITH_COMMENT,
    DB_TA_SELECT_TICKET_ASSIGNMENTS_BY_TICKET_ID,
    DB_TA_SELECT_CURRENT_TICKET_ASSIGNMENT_BY_TICKET_ID,
    DB_TA_DELETE_EMPLOYEE_ASSIGNMENT,

    // ticket_attachment table
    DB_TATT_INSERT_NEW_TICKET_ATTACHMENT,
    DB_TATT_INSERT_EMPTY,
    DB_TATT_UPDATE_META,
    DB_TATT_SELECT_TICKET_ATTACHMENTS_BY_TICKET_ID,
    DB_TATT_SELECT_BY_ID,

    // ticket_comment table
    DB_TC_INSERT_NEW_TICKET_COMMENT,
    DB_TC_SELECT_TICKET_COMMENTS_BY_TICKET_ID,
    DB_TC_UPDATE_COMMENT_MARK_AS_DELETED,

    // ticket_status_history table
    DB_TSH_INSERT_NEW_TICKET_STATUS_HISTORY,
    DB_TSH_SELECT_TICKET_STATUS_HISTORY_BY_TICKET_ID,

    // CI - caller_information
    DB_CI_INSERT_NEW_CALLER,
    DB_CI_SELECT_ALL_CALLERS, // limit 100
    DB_CI_SELECT_CALLER_AFTER_INSERT,
    DB_CI_SELECT_CALLER_BY_ID,
    DB_CI_DELETE_CALLER_BY_ID,
    DB_CI_UPDATE_CALLER_BY_ID,

    // Employee Information
    DB_EI_INSERT_EMPLOYEE,
    DB_EI_SELECT_ALL_EMPLOYEES,
    DB_EI_SELECT_EMPLOYEE_AFTER_INSERT,
    DB_EI_SELECT_EMPLOYEE_BY_ID,
    DB_EI_UPDATE_EMPLOYEE_BY_ID,
    DB_EI_DELETE_EMPLOYEE_BY_ID,

    // machine list
    DB_ML_SELECT_ALL_MACHINES,
    DB_ML_SELECT_MACHINE_BY_ID,

    // Misc
    DB_SELECT_LAST_INSERT_ID,
    DB_TICKET_SELECT_TITLE_DESC_BY_ID,
    DB_TICKET_REPORT_SELECT_PLAIN_BY_TICKET_ID,

    // crypto_keys
    DB_CS_SELECT_BY_NAME,
    DB_CS_UPDATE_KEY,
    DB_CS_INSERT_NEW_KEY,

    // contractor_visit CV
    DB_CV_INSERT_NEW_CONTRACTOR_VISIT,
    DB_CV_SELECT_CONTRACTOR_VISITS,
    DB_CV_SELECT_OVERVIEW,
    DB_CV_SELECT_BY_ID,
    DB_CV_UPDATE_CONTRACTOR_VISIT_BY_ID,

    // ticket_spare_parts_used TSPU
    DB_TSPU_INSERT_NEW_SPARE_PART_USED,
    DB_TSPU_SELECT_SPARE_PARTS_USED_BY_TICKET_ID,
    DB_TSPU_SELECT_SPARE_PART_USED_FOR_TICKET_VIEW_BY_ID,
    DB_TSPU_SOFT_DELETE_BY_ID,

    // ticket_report TR
    DB_TR_INSERT_NEW_TICKET_REPORT,
    DB_TR_SELECT_TICKET_REPORTS_BY_TICKET_ID,
    DB_TR_UPDATE_TICKET_REPORT_BY_ID,

    // machine_line ML
    DB_ML_SELECT_ALL_LINES,
    DB_ML_SELECT_ALL_LINES_OVER_LOCATIONS,
    DB_ML_SELECT_LINE_BY_ID,
    DB_ML_SELECT_CAN_DELETE_LINE_BY_ID,
    DB_ML_SELECT_NAME_BY_ID,
    DB_ML_INSERT_NEW_LINE,
    DB_ML_UPDATE_LINE_BY_ID,
    DB_ML_UPDATE_RESTORE_LINE_BY_ID,
    DB_ML_DELETE_LINE_BY_ID,

    // machine_type MT
    DB_MT_SELECT_ALL_TYPES,
    DB_MT_SELECT_TYPE_BY_ID,
    DB_MT_SELECT_CAN_DELETE_TYPE_BY_ID,
    DB_MT_SELECT_NAME_BY_ID,
    DB_MT_INSERT_NEW_TYPE,
    DB_MT_UPDATE_TYPE_BY_ID,
    DB_MT_UPDATE_RESTORE_TYPE_BY_ID,
    DB_MT_DELETE_TYPE_BY_ID,

    // machine_manufacturer MM
    DB_MM_SELECT_ALL_MANUFACTURERS,
    DB_MM_SELECT_MANUFACTURER_BY_ID,
    DB_MM_SELECT_CAN_DELETE_MANUFACTURER_BY_ID,
    DB_MM_SELECT_NAME_BY_ID,
    DB_MM_INSERT_NEW_MANUFACTURER,
    DB_MM_UPDATE_MANUFACTURER_BY_ID,
    DB_MM_UPDATE_RESTORE_MANUFACTURER_BY_ID,
    DB_MM_DELETE_MANUFACTURER_BY_ID,

    // facility_room FR
    DB_FR_SELECT_ROOMS_BY_LOCATION,
    DB_FR_SELECT_ROOM_BY_LOCATION_ONLY,
    DB_FR_SELECT_ALL_ROOMS,
    DB_FR_SELECT_ROOM_BY_ID,
    DB_FR_SELECT_CAN_DELETE_ROOM_BY_ID,
    DB_FR_INSERT_NEW_ROOM,
    DB_FR_UPDATE_ROOM_BY_ID,
    DB_FR_UPDATE_RESTORE_ROOM_BY_ID,
    DB_FR_DELETE_ROOM_BY_ID,

    // contractor_worker CW
    DB_CW_SELECT_ALL_CONTRACTOR_WORKERS,
    DB_CW_INSERT_NEW_CONTRACTOR_WORKER,
    DB_CW_UPDATE_CONTRACTOR_WORKER_BY_ID,
    DB_CW_UPDATE_DELETE_CONTRACTOR_WORKER_BY_ID,

    // contractor_visit_worker CVW
    DB_CVW_INSERT_NEW_CONTRACTOR_VISIT_WORKER,
    DB_CVW_SELECT_WORKERS_BY_CONTRACTOR_VISIT_ID,
    DB_CVW_REPLACE_WORKERS_FOR_CONTRACTOR_VISIT_ID,
    DB_CVW_DELETE_WORKERS_FOR_CONTRACTOR_VISIT_ID,

    // contractor_visit_status CVS
    DB_CVS_SELECT_ALL_STATUS,


    MAX_VALUE
};

void RegisterAMSPreparedStatements();

} // namespace database::Implementation

