#pragma once

#include <cstdint>

#include "DatabaseTypes.h"

namespace database::Implementation
{

enum class IMSPreparedStatement : std::uint32_t
{
    DB_VS_SELECT_ACTIVE_VERSION_INFO = static_cast<std::uint32_t>(StatementName::NONE) + 1,

    // CL - Company Location
    DB_CL_SELECT_ALL_COMPANY_LOCATIONS,

    // SR - storage_rooms
    DB_SR_SELECT_ALL_ROOMS,

	// RBAC
    DB_RBAC_SELECT_ACCOUNT_PERMISSION,
    DB_RBAC_SELECT_GROUP_PERMISSION,
    DB_RBAC_SELECT_GROUP_PERMISSION_RECURSIVE,
    DB_RBAC_SELECT_LINKED_PERMISSION,
    DB_RBAC_SELECT_ACCOUNT_GROUPS,
    DB_RBAC_SELECT_GROUP_PERMISSIONS,
    DB_RBAC_SELECT_ACCOUNT_OVERRIDES,
    DB_RBAC_AUDIT_INSERT,
    DB_RBAC_SELECT_GROUP_ROLE,
    DB_RBAC_SELECT_ALL_ROLE_PERMISSIONS,
    DB_RBAC_SELECT_PERMISSION_DENIED,
    DB_RBAC_SELECT_PERMISSION_ALLOWED_OR_DENIED,
    DB_RBAC_DELETE_ACCOUNT_GROUP_BY_ID,
    DB_RBAC_DELETE_ACCOUNT_PERMISSIONS_BY_ID,

    // RBAC RAP - rbac_account_permissions
    DB_RAP_DELETR_DATA_BY_PERMISSION_AND_USER_ID,
    DB_RAP_INSERT_ACCOUNT_PERMISSION,

    // RBAC RAG - rbac_account_groups
    DB_RAG_INSERT_NEW_USER,

    // LogData
    DB_LOG_DATA_INSERT_NEW_LOG,
    DB_LOG_DATA_DELETE_OLDER_ENTRIES,

    // User
    DB_ORDER_INSERT_USER_NEW_USER,
    DB_USER_INSERT_NEW_USER_BY_CHIP_ID,
    DB_ORDER_SELECT_USER_BY_USERNAME,
    DB_ORDER_SELECT_USER_FOR_LOGIN_BY_USERNAME,
    DB_ORDER_SELECT_USER_EMAIL_BY_ID,
    DB_ORDER_SELECT_USER_ACCESS_RIGHT_BY_ID,
    DB_ORDER_SELECT_USER_PASSWORD_BY_ID,
    DB_USER_SELECT_USER_BY_CHIP_ID,
    DB_USER_SELECT_USER_BY_ID,
    DB_USER_DELETE_BY_USERNAME,
    // New Changes
    DB_RAG_INSERT_RBAC_ACCESS,
    DB_USER_DATA_UPDATE_FIRST_NAME_BY_USERID,
    DB_USER_DATA_UPDATE_LAST_NAME_BY_USERID,
    DB_USER_UPDATE_CHANGE_USER_NAME,
    DB_USER_UPDATE_PASSWORD,
    DB_USER_UPDATE_MAIL_ADDRESS,
    DB_USER_UPDATE_ACCESS_RIGHT_BY_ID,
    DB_USER_DATA_UPDATE_MAIL_BODY_OFFER,
    DB_USER_DATA_UPDATE_MAIL_SUBJECT_OFFER,
    DB_USER_DATA_UPDATE_MAIL_BODY_ORDER,
    DB_USER_DATA_UPDATE_MAIL_SUBJECT_ORDER,
    DB_RAG_DELETE_OLD_ACCESS,
    DB_USER_DELETE_USER_BY_ID,
    DB_USER_DATA_DELETE_USER_DATA_BY_ID,
    // Delete User -> user, user_data, rbac_account_groups, rbac_account_permissions
    DB_RAP_DELETE_DATA_BY_USER_ID,
    // User Data
    DB_ORDER_INSERT_USER_DATA_NEW_USER,
    DB_USER_DATA_INSERT_BASIC_DATA,
    DB_ORDER_SELECT_USER_DATA_BY_ID,
    DB_USER_DATA_SELECT_FOR_EXIST,
    DB_USER_DATA_INSERT_FIRST_LAST_NAME_COMBINE,
    DB_USER_DATA_UPDATE_FIRST_LAST_NAME_COMBINE,
    DB_USER_DATA_UPDATE_PERSONAL_STYLE_BY_USERID,
    DB_USER_DATA_UPDATE_PERSONAL_LANGUAGE_BY_USERID,
    DB_ORDER_DELETE_USER_DATA_BY_ID,
    // Selects before new User Add
    DB_ORDER_SELECT_USERNAME_BY_USERNAME,
    DB_ORDER_SELECT_EMAIL_BY_EMAIL,
    DB_ORDER_SELECT_ACCESS_RIGHT_BY_USERNAME,
    DB_USER_SELECT_CHIP_ID,
    DB_USER_SELECT_ON_START,
    DB_USER_UPDATE_RFID_BY_ID,
    DB_USER_UPDATE_USER_ACCESS_RIGHT_BY_ID,

    // MT - Message Translation
    DB_MT_SELECT_TRANSLATION_BY_LANGUAGE_AND_KEY,

    // CCU - company_cost_units
    DB_CCU_SELECT_ALL_COST_UNITS,

    // GB - global_settings
    DB_GS_LOAD_LOCAL_FILE_ROOT_PATH,

    // article_database AD
    DB_AD_SELECT_ARTICLE_NAME_BY_ID,

    // company_contact_data CCD
    DB_CCD_SELECT_ALL_COMPANY_CONTACTS,

    MAX_VALUE
};

void RegisterIMSPreparedStatements();

} // namespace database::Implementation
