function(safe_glob_dlls result_var directory)
    if(EXISTS "${directory}" AND IS_DIRECTORY "${directory}")
        file(GLOB _found_dlls "${directory}/*.dll")
        set(${result_var} ${_found_dlls} PARENT_SCOPE)
    else()
        message(WARNING "safe_glob_dlls: '${directory}' ist ungültig – kein GLOB durchgeführt.")
        set(${result_var} "" PARENT_SCOPE)
    endif()
endfunction()